quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=gymtracker
quarkus.datasource.password=gymtracker
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gymtracker

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.http.root-path=/api

jwt.access-token.duration=900
jwt.refresh-token.duration=604800
