quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=gymtracker
quarkus.datasource.password=gymtracker
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gymtracker

quarkus.hibernate-orm.database.generation=drop-and-create
